let data = [
    { nome: "Fruticultura Tropical e Subtropical", codigo: "AGB0450" },
    { nome: "Irrigação e Drenagem", codigo: "AGB0448" },
    { nome: "Manejo de Plantas Daninhas", codigo: "AGB0445" },
    { nome: "Manejo e Conservação do Solo", codigo: "AGB0451" },
    { nome: "Olericultura", codigo: "AGB0435" },
    { nome: "Perícia Agrícola e Ambiental", codigo: "AGB0429" },
    { nome: "Tecnologia de Produtos de Origem Vegetal", codigo: "AGB0467" },
    { nome: "Administração Rural", codigo: "AGB0449" },
    { nome: "Apicultura", codigo: "AGA0424" },
    { nome: "Biotecnologia Vegetal", codigo: "AGB0492" },
    { nome: "Fitopatologia Agrícola", codigo: "AGB0438" },
    { nome: "Geoprocessamento", codigo: "AGB0441" },
    { nome: "Hidráulica Agrícola", codigo: "AGB0440" },
    { nome: "Manejo e Utilização de Pastagens", codigo: "AGB0439" },
    { nome: "Metodologia Científica", codigo: "AGC0414" },
    { nome: "Nutrição Vegetal", codigo: "AGB0444" },
    { nome: "Agroecologia", codigo: "AGB0418" },
    { nome: "Biologia do Solo", codigo: "AGB0434" },
    { nome: "Bovinocultura de Leite", codigo: "AGB0447" },
    { nome: "Economia e Mercado Agrícola", codigo: "AGB0443" },
    { nome: "Entomologia Agrícola", codigo: "AGB0431" },
    { nome: "Fitopatologia Geral", codigo: "AGB0432" },
    { nome: "Hidrologia Agrícola", codigo: "AGB0437" },
    { nome: "Melhoramento Animal", codigo: "AGB0436" },
    { nome: "Melhoramento Vegetal", codigo: "AGB0433" },
    { nome: "Tecnologia de Produção de Sementes", codigo: "AGB0446" },
    { nome: "Entomologia Geral", codigo: "AGB0425" },
    { nome: "Experimentação Agrícola", codigo: "AGB0424" },
    { nome: "Fertilidade do Solo", codigo: "AGB0442" },
    { nome: "Fisiologia Vegetal", codigo: "AGB0428" },
    { nome: "Microbiologia Agrícola", codigo: "AGB0426" },
    { nome: "Nutrição Animal", codigo: "AGB0427" },
    { nome: "Topografia II", codigo: "AGB0430" },
    { nome: "Agrometeorologia e Climatologia", codigo: "AGB0417" },
    { nome: "Bioquímica", codigo: "AGB0416" },
    { nome: "Estatística", codigo: "AGB0422" },
    { nome: "Física do Solo", codigo: "AGB0419" },
    { nome: "Genética", codigo: "AGB0420" },
    { nome: "Morfologia Vegetal", codigo: "AGB0407" },
    { nome: "Topografia I", codigo: "AGB0423" },
    { nome: "Zoologia Agrícola", codigo: "AGB0421" },
    { nome: "Anatomia e Fisiologia Animal", codigo: "AGB0410" },
    { nome: "Botânica Sistemática", codigo: "AGB0413" },
    { nome: "Cálculo Diferencial Integral", codigo: "AGB0408" },
    { nome: "Gênese e Classificação dos Solos", codigo: "AGB0412" },
    { nome: "Mecanização Agrícola", codigo: "AGB0411" },
    { nome: "Química Analítica", codigo: "AGB0409" },
    { nome: "Sociologia Rural", codigo: "AGB0415" },
    { nome: "Biologia", codigo: "AGB0405" },
    { nome: "Desenho Técnico", codigo: "AGB0406" },
    { nome: "Física", codigo: "AGB0401" },
    { nome: "Introdução à Agronomia", codigo: "AGB0403" },
    { nome: "Matemática", codigo: "AGB0402" },
    { nome: "Química Geral e Orgânica", codigo: "AGB0404" }
];